# Generated by Django 6.0.1 on 2026-05-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyactivity',
            options={'ordering': ['-date']},
        ),
    ]
