# Generated by Django 6.0.1 on 2026-09-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutchArticleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(blank=True, max_length=150)),
                ('correct_article', models.CharField(choices=[('de', 'de'), ('het', 'het')], max_length=3)),
                ('explanation', models.TextField()),
                ('category', models.CharField(choices=[('plural', 'Plural'), ('person', 'Person'), ('diminutive', 'Diminutive -je'), ('ing', '-ing'), ('heid', '-heid'), ('memorize', 'Memorize')], max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2')], default='A1', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
