# Generated by Django 6.0.1 on 2026-05-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ['-answered_at']},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={'ordering': ['-started_at']},
        ),
    ]
