# Generated by Django 6.0.1 on 2026-01-19 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dutch", models.CharField(max_length=200)),
                ("translation", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[("EN", "English-Dutch"), ("RU", "Russian-Dutch")], max_length=2
                    ),
                ),
                ("part_of_speech", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["dutch"],
                "unique_together": {("dutch", "translation", "source")},
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "box",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
                    ),
                ),
                ("next_review", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="words.word"),
                ),
            ],
            options={
                "unique_together": {("user", "word")},
            },
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("FAV", "Favorites"),
                            ("LEARN", "To Learn"),
                            ("MASTERED", "Mastered"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("words", models.ManyToManyField(related_name="lists", to="words.word")),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
    ]
