# Generated by Django 6.0.1 on 2026-02-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_category_categorizedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('EN', 'English-Dutch'), ('UK', 'Ukrainian-Dutch')], max_length=2),
        ),
    ]
