# Generated by Django 6.0.1 on 2026-04-03 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_word_example_translation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorizedword',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wordlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='box',
            field=models.IntegerField(choices=[(1, 'Box 1'), (2, 'Box 2'), (3, 'Box 3'), (4, 'Box 4'), (5, 'Box 5')], default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('EN', 'English-Dutch'), ('UK', 'Ukrainian-Dutch')], default='EN', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='categorizedword',
            constraint=models.UniqueConstraint(fields=('word', 'category'), name='unique_word_category'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='unique_user_word_flashcard'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('dutch', 'translation', 'source'), name='unique_word_translation_source'),
        ),
        migrations.AddConstraint(
            model_name='wordlist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_list_name'),
        ),
    ]
