# Generated by Django 6.0.1 on 2026-05-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_alter_categorizedword_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categorizedword',
            name='unique_word_category',
        ),
        migrations.RemoveField(
            model_name='categorizedword',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorizedword',
            name='word',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategorizedWord',
        ),
    ]
