# Generated by Django 6.0.1 on 2026-05-17 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_remove_category_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='dutch',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('EN', 'English-Dutch'), ('UK', 'Ukrainian-Dutch')], db_index=True, default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'next_review'], name='idx_user_next_review'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'box'], name='idx_user_box'),
        ),
        migrations.AddConstraint(
            model_name='example',
            constraint=models.UniqueConstraint(fields=('word', 'text'), name='unique_word_example'),
        ),
    ]
