# Generated by Django 6.0.1 on 2026-05-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_alter_flashcard_next_review_alter_word_dutch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('SYN', 'Synonym'), ('ANT', 'Antonym'), ('HYP', 'Hypernym'), ('HPO', 'Hyponym'), ('MER', 'Meronym'), ('HOL', 'Holonym'), ('REL', 'Related'), ('DER', 'Derived')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='words.word')),
                ('word_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_in', to='words.word')),
            ],
            options={
                'ordering': ['word_from', 'relation_type'],
                'constraints': [models.UniqueConstraint(fields=('word_from', 'word_to', 'relation_type'), name='unique_word_relation')],
            },
        ),
    ]
