# Generated by Django 6.0.1 on 2026-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_wordrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.CharField(choices=[('EN', 'English-Dutch'), ('RU', 'Russian-Dutch'), ('UK', 'Ukrainian-Dutch')], db_index=True, default='EN', max_length=2),
        ),
    ]
