# Generated by Django 6.0.1 on 2026-09-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_wordgenerationjob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordrelation',
            name='unique_word_relation',
        ),
        migrations.DeleteModel(
            name='WordRelation',
        ),
    ]
