# Generated by Django 6.0.1 on 2026-09-22 21:32

from django.db import migrations, models
from django.db.models import Count


def dedupe_words(apps, schema_editor):
    Word = apps.get_model("words", "Word")
    Example = apps.get_model("words", "Example")
    Flashcard = apps.get_model("words", "Flashcard")
    QuizAnswer = apps.get_model("quiz", "QuizAnswer")

    dup_groups = (
        Word.objects.values("dutch", "source")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    total = 0
    for group in dup_groups:
        words = list(
            Word.objects.filter(
                dutch=group["dutch"], source=group["source"]
            ).order_by("id")
        )
        keeper = words[0]
        for loser in words[1:]:
            for example in Example.objects.filter(word=loser):
                keeper.examples.get_or_create(
                    word=keeper,
                    text=example.text,
                    defaults={
                        "translation": example.translation,
                        "created_by": example.created_by,
                    },
                )
            for flashcard in Flashcard.objects.filter(word=loser):
                Flashcard.objects.get_or_create(
                    user=flashcard.user,
                    word=keeper,
                    defaults={
                        "box": flashcard.box,
                        "next_review": flashcard.next_review,
                        "last_reviewed": flashcard.last_reviewed,
                    },
                )
            QuizAnswer.objects.filter(word=loser).update(word=keeper)
            loser.lists.through.objects.filter(word_id=loser.id).update(word_id=keeper.id)
            loser.delete()
            total += 1
    if total:
        print(f"Deduplicated {total} duplicate word rows")


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0015_remove_wordrelation_unique_word_relation_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_words, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_translation_source',
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('dutch', 'source'), name='unique_word_dutch_source'),
        ),
    ]
